
bind \ split-window -h
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

set-option -g default-terminal "screen-256color"
# set-option -g terminal-overrides "screen-256color"



unbind %



# VIM keybinds for tmux - require plugin
setw -g mode-keys vi
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L

set-option -g mouse on
set-option -g allow-rename on


# Default history limit is 2000
set-option -g history-limit 5000

# Starts first pane with number 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# automatic renumber windows
set -g renumber-windows on

# Catppuccin plugin configurations
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory" # date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.2'

set -g status-position top




run "~/.tmux/plugins/tpm/tpm"

